import os
import numpy as np
import pandas as pd

# load configuration
# -----------------------------------------------------
configfile: "config/config.yml"

# read sample sheet
samples = (
    pd.read_csv(config["samplesheet"], sep="\t", dtype={"sample": str, "lane": str})
    .set_index(["sample", "lane"], drop=False)
)

FASTQC_HTML_OUTPUTS = [
    os.path.join("results/qc/fastqc", f"{row.sample}.L{row.lane}.{read}.html")
    for row in samples.itertuples(index=False)
    for read in ["r1", "r2"]
]

FASTQC_ZIP_OUTPUTS = [
    os.path.join("results/qc/fastqc", f"{row.sample}.L{row.lane}.{read}_fastqc.zip")
    for row in samples.itertuples(index=False)
    for read in ["r1", "r2"]
]

MAPPING_OUTPUTS = [
    os.path.join("results/mapped", f"{row.sample}-{row.lane}.sorted.bam")
    for row in samples.itertuples(index=False)
]

DEDUP_OUTPUTS = [
    os.path.join("results/dedup", f"{row.sample}-{row.lane}.bam")
    for row in samples.itertuples(index=False)
]

localrules: multiqc_fastqc

# target rules
# -----------------------------------------------------
rule all:
    input:
        "reports/multiqc/fastqc.html",
        "results/multiqc/fastqc_data.zip",
        DEDUP_OUTPUTS,

rule fastqc:
    input:
        lookup(query="sample == '{sample}' & lane == '{lane}'", within=samples, cols="{read}")
    output:
        html="results/qc/fastqc/{sample}.L{lane}.{read}.html",
        zip="results/qc/fastqc/{sample}.L{lane}.{read}_fastqc.zip", # the suffix _fastqc.zip is necessary for multiqc to find the file. If not using multiqc, you are free to choose an arbitrary filename
    params:
        extra = "--quiet"
    log:
        "logs/fastqc/{sample}.{lane}.{read}.log"
    threads: 1
    resources:
        mem_mb=1024,
    wrapper:
        "v5.7.0/bio/fastqc"

rule multiqc_fastqc:
    input:
        FASTQC_HTML_OUTPUTS,
        FASTQC_ZIP_OUTPUTS,
    output:
        "reports/multiqc/fastqc.html",
        "results/multiqc/fastqc_data.zip",
    params:
        extra="--verbose",  # Optional: extra parameters for multiqc.
    log:
        "logs/multiqc.log",
    wrapper:
        "v8.1.1/bio/multiqc"

def get_fastq(wildcards):
    """Get fastq files of given sample-lane."""
    fastqs = samples.loc[(wildcards.sample, wildcards.lane), ["r1", "r2"]].dropna()
    return [fastqs.r1, fastqs.r2]

rule map_reads:
    input:
        reads=get_fastq,
        idx=multiext(config["bwa"]["index"], ".amb", ".ann", ".bwt", ".pac", ".sa"),
    output:
        temp("results/mapped/{sample}-{lane}.sorted.bam"),
    log:
        "logs/bwa_mem/{sample}-{lane}.log",
    params:
        extra=r"-R '@RG\tID:{sample}\tSM:{sample}'",
        sorting="samtools",  # Can be 'none', 'samtools' or 'picard'.
        sort_order="coordinate",  # Can be 'queryname' or 'coordinate'.
        sort_extra="",  # Extra args for samtools/picard.
    threads: 8
    resources:
        mem="16G",
        runtime="1h",
    wrapper:
        "v9.0.0/bio/bwa/mem"

rule mark_duplicates:
    input:
        bams="results/mapped/{sample}-{lane}.sorted.bam",
    output:
        bam=temp("results/dedup/{sample}-{lane}.bam"),
        metrics="results/qc/dedup/{sample}-{lane}.metrics.txt",
    log:
        "logs/picard/dedup/{sample}-{lane}.log",
    params:
        extra="--REMOVE_DUPLICATES true",
    threads: 8
    resources:
        mem="16G",
        runtime="1h",
    wrapper:
        "v9.0.0/bio/picard/markduplicates"
