# load configuration
# -----------------------------------------------------
configfile: "config/config.yml"

# target rules
# -----------------------------------------------------
rule all:
    input:
        "results/cellranger_mkref",

# Make cellranger reference
# -----------------------------------------------------
rule cellranger_mkref:
    input:
        fasta=config["cellranger"]["mkref"]["fasta"],
        gtf=config["cellranger"]["mkref"]["gtf"],
    output:
        directory("results/cellranger_mkref"),
    params:
        genome=config["cellranger"]["mkref"]["genome"],
    message:
        """--- Make cellranger reference."""
    threads: 1
    resources:
        mem="32G",
        mem_gb=32,
        runtime="30m",
    log:
        "logs/cellranger_mkref.log",
    shell:
        " cellranger mkref"
        "  --genome {params.genome}"
        "  --fasta {input.fasta}"
        "  --genes {input.gtf}"
        "  --nthreads {threads}"
        "  --memgb {resources.mem_gb}"
        "  --output-dir {output}"
        "  2> {log} "
