# load configuration
# -----------------------------------------------------
configfile: "config/config.yml"

# target rules
# -----------------------------------------------------
rule all:
    input:
        "results/cellranger_mkref",

# Make cellranger reference
# -----------------------------------------------------
rule cellranger_mkref:
    input:
        fasta=config["cellranger"]["mkref"]["fasta"],
        gtf=config["cellranger"]["mkref"]["gtf"],
    output:
        directory("results/cellranger_mkref"),
    params:
        genome=config["cellranger"]["mkref"]["genome"]
    message:
        """--- Make cellranger reference."""
    threads: 1
    resources:
        mem="32G"
        runtime="30m",
    log:
        "logs/cellranger_mkref.log",
    shell:
        "mkdir -p tmp &&"
        " gunzip -c {input.fasta} > tmp/genome.fa &&"
        " cellranger mkref"
        "  --genome {params.genome}"
        "  --fasta tmp/genome.fa"
        "  --genes {input.gtf}"
        "  --nthreads {threads}"
        "  --memgb {resources.mem_gb}"
        "  --output-dir {output}"
        "  2> {log} &&"
        " rm -rf tmp"
