---
title: "report"
format: html
---

```{r}
#| message: false
library(ggplot2)
library(readr)
```

```{r}
# vireo_data <- read_tsv(
#   file = "/ceph/project/goodwin/albrecht/round2/vireo_gatk/results/vireo/S1/donor_ids.tsv",
#   show_col_types = FALSE
# )
# vireo_data
samples <- paste0("S", 1:8)

vireo_data <- map_dfr(samples, function(s) {
  read_tsv(
    file = file.path(
      "/ceph/project/goodwin/albrecht/round2/vireo_gatk/results/vireo",
      s,
      "donor_ids.tsv"
    ),
    show_col_types = FALSE
  ) %>%
    mutate(sample = s, .before = 1)
})
vireo_data
```

```{r}
vireo_summary <- vireo_data |> 
  summarise(
    n = n(), .by = c(sample, donor_id)
  )
vireo_summary
```

```{r}
total_assigned <- vireo_summary |> 
  filter(!donor_id %in% c("unassigned", "doublet")) |> 
  summarise(total = sum(n)) |> 
  pull(total)
ggplot(vireo_summary, aes(x = donor_id, y = n, colour = sample)) +
  geom_line(aes(group = sample)) +
  labs(
    subtitle = stringr::str_glue("Uniquely assigned: {total}", total = format(total_assigned, big.mark = ","))
  ) +
  coord_cartesian(ylim = c(0, NA)) +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)
  )
```

```{r}
total_assigned_per_sample <- vireo_summary |> 
  filter(donor_id %in% c("unassigned", "doublet")) |> 
  summarise(total = sum(n), .by = sample)
ggplot(vireo_summary, aes(x = donor_id, y = n, colour = sample)) +
  geom_line(aes(group = sample)) +
  labs(
    subtitle = stringr::str_glue("Uniquely assigned: {total}", total = format(total_assigned, big.mark = ","))
  ) +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)
  )
```

```{r}
ggplot(vireo_data, aes(x = donor_id, y = n_vars)) +
  geom_violin(scale = "width") +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)
  )
```
