---
title: "Demultiplexing report"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 4
---

```{r library, include=FALSE}
library(dplyr)
library(DropletUtils)
library(ggplot2)
library(purrr)
library(readr)
library(stringr)
```

```{r constants, include=FALSE}
umi_breaks <- 10^(-1:10)
umi_minor_breaks <- rep(c(1, 2, 5), 12) * (10^rep(-1:10, each = 3))
barcode_breaks <- 10^(-1:10)
barcode_minor_breaks <- 10^rep(-1:10)
scale_colour_cell_empty <- c(
  cell = "#0fbdb4",
  empty = "#e35f4b"
)
```

```{r snakemake, include=FALSE}
vireo_dirs <- snakemake@input[["vireo_dirs"]]
cellranger_h5s <- snakemake@input[["cellranger_h5s"]]
```

## Information

- **Pools:** `r str_glue("Processing {n} pools", n = length(vireo_dirs))`

```{r vireo_data, echo=FALSE}
vireo_data <- map_dfr(vireo_dirs, function(vireo_dir) {
  sample_id <- basename(vireo_dir)
  vireo_file <- file.path(vireo_dir, "donor_ids.tsv")
  read_tsv(
    file = vireo_file,
    show_col_types = FALSE
  ) %>%
    mutate(sample = sample_id, .before = 1)
})
```

```{r sce, echo=FALSE}
cellranger_h5s <- read_tsv("config/samples.tsv", show_col_types = FALSE) |> 
  pull(cellranger_h5, name = pool)
sce <- read10xCounts(samples = cellranger_h5s) # TODO list of files + uniquify sample names
```

```{r vireo_donor_id, echo=FALSE}
colData(sce) <- colData(sce) |> 
  as_tibble() |> 
  left_join(vireo_data, by = join_by(Sample == sample, Barcode == cell)) |> 
  as("DataFrame")
# sce$vireo_donor_id <- vireo_data[match(sce$Barcode, vireo_data$cell), "donor_id", drop = TRUE]
sce <- sce[, !is.na(sce$donor_id)]
```

## Sumary of Vireo results

### Number of cells assigned to each donor

```{r vireo_summary, echo=FALSE}
vireo_summary <- vireo_data |> 
  summarise(
    n = n(), .by = c(sample, donor_id)
  )
vireo_summary
```

### Total assigned barcodes per donor

```{r total_assigned, echo=FALSE}
total_assigned <- vireo_summary |> 
  filter(!donor_id %in% c("unassigned", "doublet")) |> 
  summarise(total = sum(n)) |> 
  pull(total)
ggplot(vireo_summary, aes(x = donor_id, y = n, colour = sample)) +
  geom_line(aes(group = sample)) +
  labs(
    subtitle = str_glue(
      "Uniquely assigned: {total}",
      total = format(total_assigned, big.mark = ",")
    )
  ) +
  coord_cartesian(ylim = c(0, NA)) +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)
  )
```

### Total assigned barcodes per sample

```{r total_assigned_per_sample, echo=FALSE}
total_assigned_per_sample <- vireo_summary |> 
  filter(!donor_id %in% c("unassigned", "doublet")) |> 
  summarise(total = sum(n), .by = sample)
ggplot(total_assigned_per_sample, aes(x = sample, y = total, fill = sample)) +
  geom_col(alpha = 0.25) +
  labs(
    subtitle = str_glue(
      "Uniquely assigned: {total}",
      total = format(total_assigned, big.mark = ",")
    )
  ) +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)
  )
```

### Number of variants per barcode per donor

```{r plot_nvars_by_donor, echo=FALSE}
ggplot(vireo_data, aes(x = donor_id, y = n_vars)) +
  geom_violin(scale = "width") +
  theme_bw() +
  labs(
    subtitle = str_glue(
      "Uniquely assigned: {total}",
      total = format(total_assigned, big.mark = ",")
    )
  ) +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)
  )
```

### Expression of lncRNA:roX2

```{r violin_rox2, echo=FALSE}
rox2_idx <- grep("rox2", rowData(sce)[["Symbol"]], ignore.case = TRUE)
tibble(
  rox2 = as.numeric(counts(sce)[rox2_idx, ]),
  donor_id = sce$donor_id
) |> 
  filter(rox2 > 0) |> 
  ggplot(aes(x = donor_id, y = rox2, fill = donor_id)) +
  geom_violin(scale = "width", alpha = 0.25) +
  scale_y_log10() +
  guides(
    fill = "none"
  ) +
  labs(
    title = "Expression of lncRNA:roX2",
    y = "Counts (log10 scale)",
    x = "Vireo donor ID"
  ) +
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)
  )
```
