---
title: "Quality Control - Index"
output: html_document
---

<!-- TODO: Add a statement "last updated on <date>" that is automatically updated when the report is rendered. -->

```{r libraries, include=FALSE}
library(readr)
library(stringr)
```

```{r snakemake, include=FALSE}
report_paths <- snakemake@input |>
  str_remove("reports/")
samples_info <- read_tsv(
  snakemake@params[["samples"]],
  show_col_types = FALSE
)
```

## Information

- **Experiment:** `r snakemake@params[["title"]]`

## Quality control reports

```{r, echo=FALSE, results='asis'}
stopifnot("umi_stats_all.html" %in% report_paths)
cat(str_glue("[All samples](umi_stats_all.html)"))
```

<details>
  <summary>Individual reports</summary>
  
```{r, echo=FALSE, results='asis'}
sample_reports <- grep("^umi_stats_one/", report_paths, value = TRUE)
names(sample_reports) <- fs::path_ext_remove(basename(sample_reports))
sample_reports <- sample_reports[samples_info$id]
cat(str_glue("- [{label}]({href})", label = names(sample_reports), href = sample_reports), sep = "\n")
```

</details>
