---
title: "report"
format: html
---

```{r}
#| message: false
library(dplyr)
library(readr)
library(tidyr)
```

```{r}
data <- list.files(path = "../results/vireo", pattern = "donor_ids.tsv", recursive = TRUE, full.names = TRUE) %>%
  map_dfr(load_one)
data
```

```{r}
total_assigned_by_sample <- data |> 
  filter(!donor_id %in% c("unassigned", "doublet")) |> 
  summarise(
    n = n(), .by = sample
  ) |> 
  arrange(desc(n)) |> 
  mutate(sample = factor(sample, sample))
total_assigned_by_sample
```

```{r}
total_assigned_by_sample |> 
  ggplot(aes(x = sample, y = n)) +
  geom_col(aes(fill = sample), alpha = 0.5) +
  theme_bw()
```


```{r}
total_assigned_by_donor <- data |> 
  filter(!donor_id %in% c("unassigned", "doublet")) |> 
  summarise(
    n = n(), .by = donor_id
  ) |> 
  arrange(desc(n)) |> 
  mutate(donor_id = factor(donor_id, donor_id))
total_assigned_by_donor
```


```{r}
data |>  
  filter(!donor_id %in% c("unassigned", "doublet")) |> 
  summarise(
    n = n(), .by = c(sample, donor_id)
  ) |> 
  arrange(desc(n)) |> 
  pivot_wider(names_from = donor_id, values_from = n, values_fill = 0)
```

```{r}
data |>  
  filter(!donor_id %in% c("unassigned", "doublet")) |> 
  summarise(
    n = n(), .by = c(sample, donor_id)
  ) |> 
  mutate(
    donor_id = factor(donor_id, levels(total_assigned_by_donor$donor_id))
  ) |> 
  ggplot(aes(x = donor_id, y = n, colour = sample)) +
  geom_point() +
  geom_line(aes(group = sample)) +
  theme_bw()
```

